[package]
name = "no-space-left-on-device"
version = "0.1.0"
authors = ["jasmaa <jasonmaa3955@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
